### ISSUE TITLE
As an unregistered user i would love to signup and use the gracker app to track my gym workouts 

### ISSUE THREAD

**Issue by unfazedEgnimadevspace** [unfazedEgnimadevspace/Gracker#1]
Hello @americodls 

I have started working on the signup form for the application, i am thinking of the attributes the user model is going to have

1 The user name 
2 user age
3 user weight 
4 user height 
5 email address 
6 password 
7 password confirmation 

Are there any other fields you can think off, so that i can add them to my unit tests or is it okay like this..

**Comment by americodls** [comment]
The questions I used to ask myself in situations like that are:
1. What are the minimum required for the use case I will implement?
2. Is there any harm in delaying the implementation of those not-required pieces?

Help me to answer those two questions here and we can continue the discussion, is that ok?

**Comment by unfazedEgnimadevspace** [comment]
Yeah that is okay...

The user's  name, email, password, password confirmation are the minimum use cases needed, i don't think there is any harm in delaying collecting the user's weight, height and age just yet... Why i wanted to add them was because i was thinking maybe we can later suggest a workout plan for them on signup based on these attributes but maybe i was overthinking it

**Comment by americodls** [comment]
Cool! Looks like you are in the right path.

There is a very popular gem that takes care of authentication. Its name is devise.

I would recommend to go with that because there are a few security gotchas in the authentication process that the gem will solve out of the box for us.

Try to create a homemade solution for authentication can be a good exercise, but if you want to create a production ready app, usually something like devise is the way to go.

Do you think we can go with devise gem?

**Comment by unfazedEgnimadevspace** [comment]
Hello @americodls 

So i heeded with your advice and i went on to integrate devise to handle sign up and sign in ...

I discovered that devise is not yet fully compatible with rails 7 because of hotwire.. I had some issues with the flash but it is all good now 

Any ideas on how we can move forward will be greatly appreciated ..

Thanks once again

**Comment by americodls** [comment]
You can go ahead and create a Draft PR with the code you have in place and explain what is the problem there and we can discuss on the PR.

**Comment by unfazedEgnimadevspace** [comment]
I have fixed the error already, I read an article and I fixed it... I have also pushed to the main branch

**Comment by americodls** [comment]
oh I got it now. Let's try to push the next changes through PRs so that we can discuss about the code we are pushing. I think it will be very valuable for learning purposes if is that okay for you.

**Comment by unfazedEgnimadevspace** [comment]
That's very okay.. I am sorry I should have done that

**Comment by americodls** [comment]
You don't need to be sorry at all.
We will continue learning as we go.
And I think that's good! 😁

I will take a look at the main branch later on.

**Comment by americodls** [comment]
If the changes you have pushed solve this issue you can go ahead and close it. 😉

**Comment by unfazedEgnimadevspace** [comment]
The UI is not looking quite great yet so I want to work on it

**Comment by unfazedEgnimadevspace** [comment]
Should i go ahead with the sign in and sign up forms ui

**Comment by americodls** [comment]
Sure. Go ahead. PRs are better if you want feedbacks.
Let's close this issue.
