### ISSUE TITLE
Link to start freestyle trainning in the initial page

### ISSUE THREAD

**Issue by americodls** [unfazedEgnimadevspace/Gracker#22]
I think is missing in the app an initial link or button to getting started.
How the user is supposed to start recording their first training?
And after that? the training will be registered in any place?
They will be able to review their training and maybe update anything if they want.

The initial page is empty.
Probably we should display the last 10 pieces of training the user has recorded and a button to record a new training.

Let's make it usable.

Wdyt?

**Comment by unfazedEgnimadevspace** [comment]
Are we gonna have two home pages, the one for authenticated users and unauthenticated users each residing in the app and website directory separately, and which controller is gonna handle serving the home page for authenticated users

Thanks
