### ISSUE TITLE
Require authentication for "/"

### ISSUE THREAD

**Issue by americodls** [unfazedEgnimadevspace/Gracker#3]
As an unauthenticated user, I should not be allowed to access the root path of this application.

Instead, I should be redirected to the sign-in page and only after being properly authenticated, I should be redirected back to the "/" path.

**Comment by unfazedEgnimadevspace** [comment]
Hello,

Okay i will work on that right away, i think devise also provides authorization as well?

I have designed forms for the login and sign up functionalities... , i also created a pull request so we can both look at the code together...

Thank you
