### ISSUE TITLE
Let's follow Ruby conventions

### ISSUE THREAD

**Issue by americodls** [unfazedEgnimadevspace/Gracker#9]
I think would be a good idea if we started following the standards and conventions of the Ruby language.

I could do that on the PRs, telling you what I know but I think we can save a lot of review time by using Rubocop.

Rubocop is a tool that checks the codebase against style/conventions.

I found this article that explains how to install and configure rubocop in an existent project:

https://danielabaron.me/blog/add-rubocop-to-legacy-project/

**Comment by unfazedEgnimadevspace** [comment]
Hello @americodls 

I followed your advice and tried adding rubocop to the project, but it is making some much changes to the code that i am scared at this point that something might break

**Comment by americodls** [comment]
I think you can install it and run it for the first time with the option `--regenerate-todo`. This will create a list that we can take car of later.

After that we can run it every time before create a new commit.

At least the new code we will write will be following all the conventions .


More info here: https://docs.rubocop.org/rubocop/1.46/usage/basic_usage.html
